const express = require('express');
const router = express.Router();

const imageController = require('../controllers/image.controller');

router.get('/dressStyle/one/1040', imageController.dressStyleOne1040);
router.get('/dressStyle/one/700', imageController.dressStyleOne700);
router.get('/dressStyle/two/1040', imageController.dressStyleTwo1040);
router.get('/dressStyle/two/700', imageController.dressStyleTwo700);

router.get('/carousel/nike', imageController.nike);
router.get('/carousel/adidas', imageController.adidas);
router.get('/carousel/66girls', imageController.girls66);
router.get('/carousel/aes', imageController.aes);
router.get('/carousel/anowherman', imageController.anowherman);
router.get('/carousel/beams', imageController.beams);
router.get('/carousel/bershka', imageController.bershka);
router.get('/carousel/burberry', imageController.burberry);
router.get('/carousel/celine', imageController.celine);
router.get('/carousel/champion', imageController.champion);
router.get('/carousel/chanel', imageController.chanel);
router.get('/carousel/chuu', imageController.chuu);
router.get('/carousel/clubmonaco', imageController.clubmonaco);
router.get('/carousel/coach', imageController.coach);
router.get('/carousel/coen', imageController.coen);
router.get('/carousel/converse', imageController.converse);
router.get('/carousel/darkvictory', imageController.darkvictory);
router.get('/carousel/dior', imageController.dior);
router.get('/carousel/fila', imageController.fila);
router.get('/carousel/g2000', imageController.g2000);
router.get('/carousel/gap', imageController.gap);
router.get('/carousel/genquo', imageController.genquo);
router.get('/carousel/gievesandhawkes', imageController.gievesandhawkes);
router.get('/carousel/globalwork', imageController.globalwork);
router.get('/carousel/goopi', imageController.goopi);
router.get('/carousel/gu', imageController.gu);
router.get('/carousel/gucci', imageController.gucci);
router.get('/carousel/guerrillagroup', imageController.guerrillagroup);
router.get('/carousel/handm', imageController.handm);
router.get('/carousel/hotping', imageController.hotping);
router.get('/carousel/ifandn', imageController.ifandn);
router.get('/carousel/ig', imageController.ig);
router.get('/carousel/lativ', imageController.lativ);
router.get('/carousel/lovfee', imageController.lovfee);
router.get('/carousel/lowrysfarm', imageController.lowrysfarm);
router.get('/carousel/maddness', imageController.maddness);
router.get('/carousel/massimodutti', imageController.massimodutti);
router.get('/carousel/meierdotq', imageController.meierdotq);
router.get('/carousel/michaelkors', imageController.michaelkors);
router.get('/carousel/mouggan', imageController.mouggan);
router.get('/carousel/nb', imageController.nb);
router.get('/carousel/nerdy', imageController.nerdy);
router.get('/carousel/nikoand', imageController.nikoand);
router.get('/carousel/ninetheory', imageController.ninetheory);
router.get('/carousel/ob', imageController.ob);
router.get('/carousel/offwhite', imageController.offwhite);
router.get('/carousel/oneboy', imageController.oneboy);
router.get('/carousel/oqliq', imageController.oqliq);
router.get('/carousel/pazzo', imageController.pazzo);
router.get('/carousel/phantaci', imageController.phantaci);
router.get('/carousel/professordote', imageController.professordote);
router.get('/carousel/pullandbear', imageController.pullandbear);
router.get('/carousel/puma', imageController.puma);
router.get('/carousel/queenshop', imageController.queenshop);
router.get('/carousel/sealson', imageController.sealson);
router.get('/carousel/spao', imageController.spao);
router.get('/carousel/sstandc', imageController.sstandc);
router.get('/carousel/stayreal', imageController.stayreal);
router.get('/carousel/stussy', imageController.stussy);
router.get('/carousel/suitangtang', imageController.suitangtang);
router.get('/carousel/suitsupply', imageController.suitsupply);
router.get('/carousel/superdry', imageController.superdry);
router.get('/carousel/supreme', imageController.supreme);
router.get('/carousel/syndro', imageController.syndro);
router.get('/carousel/th', imageController.th);
router.get('/carousel/tiffany', imageController.tiffany);
router.get('/carousel/ua', imageController.ua);
router.get('/carousel/uq', imageController.uq);
router.get('/carousel/ur', imageController.ur);
router.get('/carousel/vans', imageController.vans);
router.get('/carousel/wd', imageController.wd);
router.get('/carousel/wisdom', imageController.wisdom);
router.get('/carousel/ysl', imageController.ysl);
router.get('/carousel/zara', imageController.zara);

module.exports = router;
